// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rruuodnshhdtdkjtpytp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJydXVvZG5zaGhkdGRranRweXRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MjQwMTEsImV4cCI6MjA3NDIwMDAxMX0.UKoepR7nj0ERYRQwYPcsdL9IgGxaNReYKMmxwte-KtA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});